Modif path coverage

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,7 +22,14 @@ jobs:
     - name: Setup .NET SDK
       uses: actions/setup-dotnet@v3
       with:
-        dotnet-version: '8.0'
+        dotnet-version: '8.0.112'
+  
+    - name: Start SonarCloud analysis
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        dotnet tool install --global dotnet-sonarscanner
+        dotnet sonarscanner begin /k:"Lingatsu_MSPR814_API_Produits" /o:"lingatsu" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="ProductApi.Tests/TestResults/" /d:sonar.verbose=true
 
     - name: Restore dependencies
       run: dotnet restore ProductApi/ProductApi.sln
@@ -32,19 +39,12 @@ jobs:
 
     - name: Run tests with coverage
       run: |
-        dotnet test ProductApi.Tests/ProductApi.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage" --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=ProductApi.Tests/TestResults/*/coverage.cobertura.xml
+        dotnet test ProductApi.Tests/ProductApi.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage" --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="TestResults/" /d:sonar.verbose=true
 
     - name: Check if coverage file exists
       run: |
         ls -R ProductApi.Tests/TestResults/
-        cat ProductApi.Tests/*/TestResults/coverage.cobertura.xml || echo "Coverage file not found"
-
-    - name: Start SonarCloud analysis
-      env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      run: |
-        dotnet tool install --global dotnet-sonarscanner
-        dotnet sonarscanner begin /k:"Lingatsu_MSPR814_API_Produits" /o:"lingatsu" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="ProductApi.Tests/TestResults/*/coverage.cobertura.xml"
+        cat ProductApi.Tests/TestResults/coverage.cobertura.xml || echo "Coverage file not found"
 
     - name: Final SonarCloud Analysis
       env:
