correction chemin relatif

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,7 +29,7 @@ jobs:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       run: |
         dotnet tool install --global dotnet-sonarscanner
-        dotnet sonarscanner begin /k:"Lingatsu_MSPR814_API_Produits" /o:"lingatsu" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="ProductApi.Tests/TestResults/" /d:sonar.verbose=true
+        dotnet sonarscanner begin /k:"Lingatsu_MSPR814_API_Produits" /o:"lingatsu" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="ProductApi.Tests/TestResults/"  
 
     - name: Restore dependencies
       run: dotnet restore ProductApi/ProductApi.sln
@@ -41,10 +41,10 @@ jobs:
       run: |
         dotnet test ProductApi.Tests/ProductApi.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage" --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="TestResults/"
 
-    - name: Check if coverage file exists
-      run: |
-        ls -R ProductApi.Tests/TestResults/
-        cat ProductApi.Tests/TestResults/coverage.cobertura.xml || echo "Coverage file not found"
+    # - name: Check if coverage file exists
+    #   run: |
+    #     ls -R ProductApi.Tests/TestResults/
+    #     cat ProductApi.Tests/TestResults/coverage.cobertura.xml || echo "Coverage file not found"
 
     - name: Final SonarCloud Analysis
       env:
